resources:
- name: daily-trigger
  type: time
  source:
    interval: 24h

- name: one-time-trigger
  type: time
  source:
    interval: 999999h

- name: configuration
  type: git
  source:
    private_key: ((git_deploy_key.private_key))
    uri: ((git_uri))
    branch: master
    submodules: all
    depth: 1

- name: opsman-product
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: pcf-vsphere-(.*).ova

- name: installation
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: installation-(.*).zip

- name: platform-automation-tasks
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: platform-automation-image-(.*).tgz

jobs:
  - name: install-opsman
    serial: true
    serial_groups: [ install ]
    plan:
      - aggregate:
          - get: platform-automation-image
            params:
              unpack: true
          - get: one-time-trigger
            trigger: true
          - get: platform-automation-tasks
            params:
              unpack: true
          - get: opsman-product
          - get: configuration
      - task: credhub-interpolate
        image: platform-automation-image
        file: platform-automation-tasks/tasks/credhub-interpolate.yml
        params:
          CREDHUB_CLIENT: ((credhub_client))
          CREDHUB_SECRET: ((credhub_secret))
          CREDHUB_SERVER: ((credhub_server))
          CREDHUB_CA_CERT: ((credhub_ca_cert.certificate))
          PREFIX: '/foundations/sandbox'
          INTERPOLATION_PATH: '.'
        input_mapping:
          files: configuration
        output_mapping:
          interpolated-files: interpolated-config
      - task: create-vm
        image: platform-automation-image
        file: platform-automation-tasks/tasks/create-vm.yml
        input_mapping:
          image: opsman-product
          state: interpolated-config
          config: interpolated-config
        params:
          STATE_FILE: state/state.yml
          OPSMAN_CONFIG_FILE: config/opsman.yml
        ensure: &make-state-commit
          do:
            - task: make-commit
              image: platform-automation-image
              file: platform-automation-tasks/tasks/make-git-commit.yml
              input_mapping: 
                repository: configuration
                file-source: generated-state
              output_mapping:
                repository-commit: configuration-commit
              params:
                FILE_SOURCE_PATH: state.yml
                FILE_DESTINATION_PATH: state/state.yml
                GIT_AUTHOR_EMAIL: "pcf-pipeline-bot@example.com"
                GIT_AUTHOR_NAME: "Platform Automation Bot"
                COMMIT_MESSAGE: 'Update state file'
            - put: configuration
              params:
                repository: configuration-commit
                merge: true
      - task: configure-authentication
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-authentication.yml
        attempts: 10
        input_mapping:
          env: interpolated-config
          config: interpolated-config
        params:
          ENV_FILE: env/env.yml
          AUTH_CONFIG_FILE: config/auth.yml
      - task: configure-director
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-director.yml
        input_mapping:
          config: interpolated-config
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml
          DIRECTOR_CONFIG_FILE: config/director.yml
      - task: apply-director-changes
        image: platform-automation-image
        file: platform-automation-tasks/tasks/apply-director-changes.yml
        input_mapping:
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml

  - name: staged-director-config
    serial: true
    plan:
      - aggregate:
          - get: platform-automation-tasks
            params: {unpack: true}
          - get: platform-automation-image
            params: {unpack: true}
          - get: configuration
      - task: credhub-interpolate
        image: platform-automation-image
        file: platform-automation-tasks/tasks/credhub-interpolate.yml
        params:
          CREDHUB_CLIENT: ((credhub_client))
          CREDHUB_SECRET: ((credhub_secret))
          CREDHUB_SERVER: ((credhub_server))
          CREDHUB_CA_CERT: ((credhub_ca_cert.certificate))
          PREFIX: '/foundations/sandbox'
          INTERPOLATION_PATH: '.'
        input_mapping:
          files: configuration
        output_mapping:
          interpolated-files: interpolated-config
      - task: staged-director-config
        image: platform-automation-image
        file: platform-automation-tasks/tasks/staged-director-config.yml
        input_mapping:
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml

  - name: export-installation
    serial: true
    plan:
      - aggregate:
          - get: daily-trigger
            trigger: true
          - get: platform-automation-image
            params:
              unpack: true
          - get: platform-automation-tasks
            params:
              unpack: true
          - get: configuration
      - task: credhub-interpolate
        image: platform-automation-image
        file: platform-automation-tasks/tasks/credhub-interpolate.yml
        params:
          CREDHUB_CLIENT: ((credhub_client))
          CREDHUB_SECRET: ((credhub_secret))
          CREDHUB_SERVER: ((credhub_server))
          CREDHUB_CA_CERT: ((credhub_ca_cert.certificate))
          PREFIX: '/foundations/sandbox'
          INTERPOLATION_PATH: '.'
        input_mapping:
          files: configuration
        output_mapping:
          interpolated-files: interpolated-config
      - task: export-installation
        image: platform-automation-image
        file: platform-automation-tasks/tasks/export-installation.yml
        input_mapping:
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml
          INSTALLATION_FILE: installation-$timestamp.zip
      - put: installation
        params:
          file: installation/installation*.zip

  - name: upgrade-opsman
    serial: true
    serial_groups: [ install ]
    plan:
      - aggregate:
          - get: one-time-trigger
            passed: [ install-opsman ]
          - get: platform-automation-image
            params:
              unpack: true
            trigger: true
          - get: platform-automation-tasks
            params:
              unpack: true
          - get: opsman-product
          - get: installation
            passed: [ export-installation ]
          - get: configuration
      - task: credhub-interpolate
        image: platform-automation-image
        file: platform-automation-tasks/tasks/credhub-interpolate.yml
        params:
          CREDHUB_CLIENT: ((credhub_client))
          CREDHUB_SECRET: ((credhub_secret))
          CREDHUB_SERVER: ((credhub_server))
          CREDHUB_CA_CERT: ((credhub_ca_cert.certificate))
          PREFIX: '/foundations/sandbox'
          INTERPOLATION_PATH: '.'
        input_mapping:
          files: configuration
        output_mapping:
          interpolated-files: interpolated-config
      - task: upgrade-opsman
        image: platform-automation-image
        file: platform-automation-tasks/tasks/upgrade-opsman.yml
        input_mapping:
          image: opsman-product
          state: interpolated-config
          config: interpolated-config
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml
          OPSMAN_CONFIG_FILE: config/opsman.yml
          STATE_FILE: state/state.yml
        ensure: *make-state-commit
      - task: apply-director-changes
        image: platform-automation-image
        file: platform-automation-tasks/tasks/apply-director-changes.yml
        input_mapping:
          env: interpolated-config
        params:
          ENV_FILE: env/env.yml