resources:
- name: platform-automation-tasks
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    endpoint: ((s3.address))
    access_key_id: ((s3.access_key))
    bucket: ((s3.bucket_name))
    secret_access_key: ((s3.secret_key))
    skip_ssl_verification: true
    regexp: platform-automation-image-(.*).tgz

jobs:
- name: test-resources
  plan:
  - aggregate:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
  - task: test-resources
    image: platform-automation-image
    file: platform-automation-tasks/tasks/test.yml