---
opsman-configuration:
  azure:
    subscription_id: {{.subscription_id}}
    resource_group_name: {{.pcf_resource_group_name}}
    tenant_id: {{.tenant_id}}
    client_id: {{.client_id}}
    client_secret: {{.client_secret}}
    network_security_group: {{.ops_manager_security_group_name}}
    vpc_subnet: /subscriptions/{{.subscription_id}}/resourceGroups/{{.pcf_resource_group_name}}/providers/Microsoft.Network/virtualNetworks/{{.network_name}}/subnets/{{.infrastructure_subnet_name}}
    public_ip: {{.ops_manager_public_ip}}
    ssh_public_key: {{.ops_manager_ssh_public_key}}
    vm_name: ops-manager-vm
    boot_disk_size: 100
    cloud_name: AzureCloud
    use_unmanaged_disk: false
    location: ((location))
    storage_account: ((storage_account_name))
    storage_key: ((storage_account_key))
    container: ((container))
